apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: aws-training-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: aws-training-ui
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
